### ISSUE TITLE
Add GitHub & Social Links for contributors and members.

### ISSUE THREAD

**Issue by mfaheemakhtar** [fcckarachi/fcckarachi.github.io#7]
I will suggest adding GitHub links for Contributors and Core Members. As of now there is only a picture and some text.

**Comment by nawazishali** [comment]
Thanks for opening the Issue @mfaheemakhtar , If you would like to solve it as well then please comment below I will share the links you need to do the task.

**Comment by mfaheemakhtar** [comment]
Yes, I would love to solve this issue.

Should I add a GitHub link at the bottom || wrap the card inside anchor tag?

![freecc](https://user-images.githubusercontent.com/17894982/36886925-835f5e88-1e10-11e8-8f6b-dca0d7d65b9b.PNG)

**Comment by nawazishali** [comment]
@mfaheemakhtar I think we should add link to Facebook profile as well. We can just place github & facebook links below just like you are already doing it and people can click on them to open the profiles. We don't need to wrap the whole card in anchor tag. What do you say? Also I would suggest reading our [Contributing guide](https://github.com/fcckarachi/fcckarachi.github.io/blob/develop/CONTRIBUTING.md) so that we follow the best practices of Git if you are not familiar with them already.

**Comment by mfaheemakhtar** [comment]
Got it.

I think LinkedIn is a better option as compare to Facebook. I mean Facebook is a kind of personal profile but on the other hand it may help getting connected easily as compare to LinkedIn.

I'm ready to go. :)

**Comment by nawazishali** [comment]
@mfaheemakhtar You can do linkedIn as well. It will only add to the overall beauty of the side. 👍 We can have all three links there. I will provide the links to all the profiles as soon as I get them.

**Comment by mfaheemakhtar** [comment]
Sure. Excited to work on it.

**Comment by nawazishali** [comment]
@mfaheemakhtar sorry it took me quite long, But here you go. Please use this [sheet](https://docs.google.com/spreadsheets/d/1vp3_FOalCHhZAv-mCjlXn4CZiAQPrbnzlh815nNNT1s/edit?usp=sharing) to get the profile urls for our contributors. It's on you what profile links you want to add.

**Comment by mfaheemakhtar** [comment]
Thanks.

**Comment by mfaheemakhtar** [comment]
@nawazishali , I've added the links and have made the pull request.
